# Generated by Django 5.2.1 on 2025-05-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("grade", models.CharField(max_length=10)),
                ("rollNumber", models.CharField(max_length=20, unique=True)),
                ("isPresent", models.BooleanField(default=True)),
                ("avatar", models.URLField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("phoneNumber", models.CharField(blank=True, max_length=20, null=True)),
                ("dateOfBirth", models.DateField(blank=True, null=True)),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "ordering": ["rollNumber"],
            },
        ),
    ]
