# Generated by Django 5.2.1 on 2025-05-25 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_id",
                    models.CharField(
                        db_index=True,
                        help_text="Grade/Class identifier, e.g., '5/1'",
                        max_length=50,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("is_present", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "student__name"],
                "unique_together": {("student", "date")},
            },
        ),
    ]
