# Generated by Django 5.2.1 on 2025-05-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("avatar", models.URLField(blank=True, null=True)),
                (
                    "classInCharge",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("dateOfBirth", models.DateField(blank=True, null=True)),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
