# Generated by Django 5.2.1 on 2025-05-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("teacher", "Teacher")],
                default="teacher",
                max_length=10,
            ),
        ),
    ]
